rpm: fix build without systemd
Fix the following error when building --without=systemd:

Processing files: grout-frr-0.16.1-20260720120706.local.el10.x86_64
error: File not found: /BUILDROOT/.../usr/lib/systemd/system/frr.service.d/grout.conf

Fixes: a6643d4302f5 ("frr: add systemd dropin to rpm/deb installed files")
Signed-off-by: Robin Jarry <rjarry@redhat.com>
Reviewed-by: Andrea Panattoni <apanatto@redhat.com>